### ISSUE TITLE
Error when cloning the repository (with suggested solution)

### ISSUE THREAD

**Issue by fethalen** [BenoitMorel/GeneRax#23]
When I run this command:

```bash
git clone --recursive git@github.com:BenoitMorel/GeneRax.git
```

I get the following error:

```bash
fatal: could not read from remote repository
```

However, I was able to download the repository using the following command instead:

```bash
git clone --recursive https://github.com/BenoitMorel/GeneRax
```

Also personally I was missing Flex and Bison and had to run:

```bash
sudo apt install flex bison
```

So you might want to add a dependencies section or something.

**Comment by BenoitMorel** [comment]
Hi fethalen,

thanks a lot for the report and the suggestions. You are right about everything :-)
I updated the readme page.

Benoit
