### ISSUE TITLE
Automatic tree generation: problematic characters retained

### ISSUE THREAD

**Issue by Neo-sage** [BenoitMorel/GeneRax#24]
Hi, I have some fasta files with the following characters in the header: **(,),|,:** which, when used to automatically generate random starting trees with GeneRax, will be retained causing a segmentation fault without specifying why.

It could be worth a warning or a note, as some tree software automatically changes those problematic characters into '_' characters, but then, if using prebuilt trees, they won't match the input alignments, this error is presented to the user though.

Also, Hi Benoit, hope you're doing well, we met on the CoME2019 course a few months ago!

**Comment by BenoitMorel** [comment]
Hi Edmund,

sorry for the late reply, it looks like I disabled notifications :(
Thanks a lot for the report, I will have a look at it. I know that we do not support the whole fasta standard, but as you wrote, we should at least return an explicit message in this case. I will also add something in the documentation.

Yes I remember you, nice to hear from you again!

Benoit

**Comment by BenoitMorel** [comment]
I added an explicit error message for unsupported characters in the alignments (available in the master branch).
Thanks again for the report :-)

**Comment by flass** [comment]
Hi there,
I had myself some issue with the presence of a square brace `]` in the alignment labels - created a problem after the starter tree was created, upon parsing it I suppose.
Great software otherwise!
Best wishes,
Florent

**Comment by BenoitMorel** [comment]
Hi Florent, 

Thanks for your feedback :-)
One issue is that some characters are perfectly valid for fasta labels, but not for taxa labels in the newick files. (this is obvious for parenthesis for instance).
One alternative solution would be to replace them with some other character, like '_' , but then you have different input and output labels...
I chose the lazy solution (forbidding special characters), but I am open to other suggestions if this can simplify your pipelines. 

Benoit

**Comment by flass** [comment]
I think it's fine - taxa should not have exotic labels in general, as this messes up not only phylogenetic programs but quite a few others, when trying to apply regexp in genome annotation files for instance. I think it's good to do some education on good practices and enforce them!
F
