### ISSUE TITLE
Number of parentheses does not match in .nhx output

### ISSUE THREAD

**Issue by kfuku52** [BenoitMorel/GeneRax#25]
Hi, First of all, thank you for developing a wonderful tool. I would like to report that the number of parentheses in the .nhx output was inconsistent in my dataset.
"("=31
")"=32

Here are the input files and some outputs including the nhx.
[Archive.zip](https://github.com/BenoitMorel/GeneRax/files/3945111/Archive.zip)

Command:
```
generax \
--species-tree "${species_tree}" \
--families generax_families.txt \
--strategy "SPR" \
--rec-model "UndatedDL" \
--prefix "generax_${og_id}" \
--seed 12345

```
Thank you.

Kenji

**Comment by BenoitMorel** [comment]
Hi Kenji,

Thanks a lot for your feedback and for your report.
This is indeed a bug. I always add one extra parenthesis at the very end of nhx outputs.
I fixed the issue on the master branch. Please let me know if the new nhx results are correct. 

Best,
Benoit

**Comment by kfuku52** [comment]
Thank you for the quick fix! I have a workaround for the bug so let me test the new version when it appears in bioconda. -Kenji
