### ISSUE TITLE
Clarification on output rates and weird transfer-less scenarios

### ISSUE THREAD

**Issue by flass** [BenoitMorel/GeneRax#28]
Hi Benoit, 

I have been successfully running GeneRax on a few gene families with protein alignment and a species tree as input, using per family rates and the undated DTL model, but I am having trouble with interpreting the output and assessing whether it is sound.

First, I have issues identifying what is what in the output due to the absence of headings in the files like the report of per-family DTL rates in `results/*/stats.txt` files: I don't know which is D, T or L.
Same with the `reconciliations/*_speciesEventCounts.txt` files, I don't know which is S, D, T or L - I assume those are the four represented events, unless one is for gene presence?  
Could you please specify the format of this output, either in the documentation or directly as a header of the files?

Second, my problem above then prevents me to fully assess the result of my run. I think there is something wrong, as none of the families had any Transfer event detected! instead the scenario came up with a very dubious combination of many D+L - just like if I was running a UndatedDL model instead of UndatedDTL, which I selected for this run.
Checking the estimated event rates in the `results/*/stats.txt` files, I see that for all families, the first one is stuck at what seems to be the minimum value, `1e-7`. One example:
```
-9489.08 -318.888
Reconciliation rates = 1e-07 0.24704 0.15936 
``` 
Maybe that first rate is the T rate, that somehow got stuck?

I was running GeneRax as compiled from the dev branch, on commit 2192e79. I'm now re-running that with the master branch, v1.1.0 released version see if it makes any difference.

here is the header of the log:
```
GeneRax was called as follow:
generax -r UndatedDTL --max-spr-radius 5 --strategy SPR -s /pantagruel_databases/Brady2019/05.core_genome/core-genome-based_reference_tree_Brady2019.full_clade_defs.nwk -f /pantagruel_databases/Brady2019/albingenes/prot_fullgenetree_GeneRax_recs/generax_prot_fullgenetree_pointestimate_2_generax.families -p /pantagruel_databases/Brady2019/albingenes/prot_fullgenetree_GeneRax_recs/generax_prot_fullgenetree_pointestimate_2/generax_prot_fullgenetree_pointestimate_2_generax --per-family-rates --reconcile 

Parameters summary: 
Families information: /pantagruel_databases/Brady2019/albingenes/prot_fullgenetree_GeneRax_recs/generax_prot_fullgenetree_pointestimate_2_generax.families
Species tree: /pantagruel_databases/Brady2019/05.core_genome/core-genome-based_reference_tree_Brady2019.full_clade_defs.nwk
Species Strategy: SPR
Strategy: SPR
Reconciliation model: UndatedDTL
DTL rates: per family rates
Prefix: /pantagruel_databases/Brady2019/albingenes/prot_fullgenetree_GeneRax_recs/generax_prot_fullgenetree_pointestimate_2/generax_prot_fullgenetree_pointestimate_2_generax
Unrooted reconciliation likelihood: OFF
Prune species tree: OFF
Reconciliation radius: 0
MPI Ranks: 8
Max gene SPR radius: 5
Gene support threshold: -1
Reconciliation likelihood weight: 1
Random seed: 123
Infer ML reconciliation: ON
```

Can you please provide some help on this one? I can supply example output files separately if needed.

All the best,

Florent

**Comment by BenoitMorel** [comment]
Hi Florent,

Indeed, a description of the output files was missing. It's now in the wiki (https://github.com/BenoitMorel/GeneRax/wiki/GeneRax#outputs)
I realized that the order of the events/rates is inconsistent among logs/outputs. I will reorganize this when I have more time (I am quite overwhelmed with the three kids at home) and keep you in touch.

In the logs, at first sight, the rates should be: dup, loss, transfers. So you should get almost no duplications, and lots of transfers. Does it make sense with the reconciliations?

**Comment by flass** [comment]
Hi Benoit, 

thank you so much for the output description, that's really helpful - which reminds me I should definitely do the same on my own software...

About the `results/*/stats.txt` rates file: it makes even less sense now, as the first, i.e. duplication rate is inferred to be super low (see excerpt above), but many duplications and no transfers are inferred in the scenarios.

Could I send you a dataset of those weird reconciliation in private (data should not made public yet) so you can have a look? 

Of course I understand if it takes you a while to return to me with an answer given the current situation.

Best wishes and good luck for the challenging organisation!

**Comment by BenoitMorel** [comment]
This is really disturbing...
Sure, send me the data I will have a look

Best wishes
Benoit

Le ven. 3 avr. 2020 à 19:01, Florent Lassalle <notifications@github.com> a
écrit :

**Comment by BenoitMorel** [comment]
Hi Florent,

this was indeed a major bug... When --per-family-rates is activated, the final reconciliation step uses the wrong rates (in particular, the transfer rate is set to 0). 
Thank you so much for the report!

I pushed a first fix on the dev branch. Please tell me if the reconciliations make more sense. 
Then I will have another careful look at how I handle the rates in the whole pipeline, merge with master, and create a tag with the fix.

Cheers,
Benoit

**Comment by flass** [comment]
ah that's brilliant, thanks for investigating this. I'll update and do some new tests.

bizarrely it did not seem like an issue with runs I did earlier this year (I think it was before release v1.1.0) where scenarios estimated with `--per-family-rates` did make sense... do you have any idea of when that bug was introduced? (I guess to be on the safe side I should re-compute those old scenarios regardless...)

**Comment by BenoitMorel** [comment]
I am no quite sure, but I think that the bug was hidden before: I think I was correcting the gene trees with per family rates, but then reconciling them with global (not per-family) rates. And at some point, I disabled the global rates estimation, and the bug became visible.
It should not make a huge difference, but maybe you should re-compute the old scenarios if that's not too much runtime... In this case, you should maybe wait for me to have checked that there is not anything else wrong with the per family rates, and that this quick fix did not introduce any issue :-)

**Comment by flass** [comment]
Hi Benoit,

I just ran the new code (from dev branch, yesterday's commit a6dfcfa) on the same data, and got similar results, with no transfer inferred but lots of duplications+losses even though the duplication rate is set at `1e-07`.
Unless I somehow kept some of the previous code active in my new build (I would not think so as I did `rm -r build/` before running again `./install.sh`), there still must be some problem in the code.
I can provide output for these if need be.
Thanks again for your help.
Cheers,
Florent

**Comment by BenoitMorel** [comment]
Hi Florent,

all my apologizes, I managed to forget one line in the previous commit. This time it should be fine.
Thanks for your patience :-)

Benoit

**Comment by flass** [comment]
Hi Benoit,

no worries at all, and thanks for fixing the program! it works perfectly now - at least it looks like it ;-) ! 
I may wait a bit indeed that you integrate all the fixes before I run all the big dataset.
I hope you enjoy your Easter break!
all the best,
Florent
