### ISSUE TITLE
nhx output is missing

### ISSUE THREAD

**Issue by kfuku52** [BenoitMorel/GeneRax#29]
Thank you for developing this useful program. I've recently updated the version to v1.1.0 using bioconda and found that this version does not generate .nhx output which was available in v1.0.0.  Is it intended behavior? Because the node annotations in nhx were quite informative, I would like to use it in my downstream analysis. Input files are attached.
[data.zip](https://github.com/BenoitMorel/GeneRax/files/4421980/data.zip)

**Comment by BenoitMorel** [comment]
Thank you for your feedback!
This was my mistake, it looks like I changed the default behavior, without documenting it. You need to add the parameter`--reconcile` to compute the reconciled tree. Sorry for the unexpected change...
Please tell me if it works, but do not close the issue (if it works, I will close when I am done with updating the documentation).

**Comment by kfuku52** [comment]
Sorry for the late response. A nhx file was correctly generated with `--reconcile`. Thank you so much!
