### ISSUE TITLE
Error reading species tree

### ISSUE THREAD

**Issue by David-Gold** [BenoitMorel/GeneRax#37]
Dear Benoît,

I am having trouble getting GeneRax to recognize my species tree. I have built the program using conda on Linux and mac systems, and I can successfully run the data in your "simulated_1" folder. This makes me think the problem is with my tree. The error message my tree file are below. Please let me know if there is any additional information you need.

Thank you for the help,
David

> [00:00:00] Filtering invalid families...
> 
> libc++abi.dylib: terminating with uncaught exception of type LibpllException: Error while reading tree from file: Species_Tree.newick
> *** Process received signal ***
> Signal: Abort trap: 6 (6)
> Signal code:  (0)
> [ 0] 0   libsystem_platform.dylib            0x00007fff6bd2142d _sigtramp + 29
> [ 1] 0   ???                                 0x0000000000000400 0x0 + 1024
> [ 2] 0   libsystem_c.dylib                   0x00007fff6bbf6a1c abort + 120
> [ 3] 0   libc++abi.dylib                     0x00007fff68c94be8 __cxa_bad_cast + 0
> [ 4] 0   libc++abi.dylib                     0x00007fff68c94d84 _ZL28demangling_terminate_handlerv + 238
> [ 5] 0   libobjc.A.dylib                     0x00007fff6a7bc792 _ZL15_objc_terminatev + 104
> [ 6] 0   libc++abi.dylib                     0x00007fff68ca1dc7 _ZSt11__terminatePFvvE + 8
> [ 7] 0   libc++abi.dylib                     0x00007fff68ca1b6c __cxa_get_exception_ptr + 0
> [ 8] 0   libc++abi.dylib                     0x00007fff68c9345d __cxa_get_globals + 0
> [ 9] 0   generax                             0x000000010c31350a _ZN13LibpllParsers18readRootedFromFileERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEE + 266
> [10] 0   generax                             0x000000010c3133cf _ZN13LibpllParsers15labelRootedTreeERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEES8_ + 15
> [11] 0   generax                             0x000000010c2ec5d3 _ZN11GeneRaxCore12initInstanceER15GeneRaxInstance + 851
> [12] 0   generax                             0x000000010c2eac55 _Z12generax_mainiPPcPv + 117
> [13] 0   generax                             0x000000010c2eb362 main + 82
> [14] 0   libdyld.dylib                       0x00007fff6bb287fd start + 1
> *** End of error message ***
> Abort trap: 6

Here is the Newick tree:

[Species_Tree.newick.txt](https://github.com/BenoitMorel/GeneRax/files/5038293/Species_Tree.newick.txt)

**Comment by BenoitMorel** [comment]
Dear David,

Thanks for your report.
The issue is that your species tree contains one polytomy. Unfortunately,
GeneRax only supports strictly bifurcating trees.
I will try to detect this case to output a better error message in the next
release.

Benoit

Le ven. 7 août 2020 à 00:25, David A. Gold <notifications@github.com> a
écrit :

**Comment by David-Gold** [comment]
Hi Benoit,

I thought I had caught all the polytomies but I missed one. I edited the tree and am no longer getting that error. A clearer error message and/or a statement on the wiki clarifying that polytomies are not allowed would be a big help.

Thank you very much for quick response! 

Best,
David
