### ISSUE TITLE
new visualizations

### ISSUE THREAD

**Issue by 444thLiao** [BenoitMorel/GeneRax#39]
I found a visualization software which is based on recphyloxml. 
But it is more usable because recommanded wesite can't not be downloaded as pdf.

here is its link. 
https://github.com/UdeS-CoBIUS/DoubleRecViz

Also, it based on recphyloxml but I found a little difference between your generated xml and his.
That just a suggestions for you to write a convertor or not

**Comment by BenoitMorel** [comment]
Hi,

thanks for your suggestion!  We are trying to move the issues/report to our new google group: https://groups.google.com/g/generaxusers
Could you please open the same question in the google group?
Best,
Benoit

**Comment by 444thLiao** [comment]
Ok, I will open a issue there.
