### ISSUE TITLE
using GeneRax on symbiont-host trees with multiple symbionts per host

### ISSUE THREAD

**Issue by Jigyasa3** [BenoitMorel/GeneRax#40]
Dear All

I wanted to ask if it is possible to use GeneRax on symbiont-host trees where we have >1 symbiont per host sample.
In a recent paper, [Satler et al 2019](https://onlinelibrary.wiley.com/doi/full/10.1111/evo.13809) showed that if there are multiple symbionts per host then its important to generate sister host tips for each symbiont per host so that there are equal no. of tips in both trees (line "shared wasp tips into two sister tips for all fig wasp species" in the paper). I wanted to confirm this step. Would GeneRax overestimate DTL events if symbiont tree tips are more than host tree tips?

Looking forward to your reply!

**Comment by BenoitMorel** [comment]
Dear Jigyasa3,

I just write you a short message to notify you that I saw your question. Unfortunately, I am on vacations until ~mid January and I don't know symbiont-host trees enough to give you a quick answer. 
In general, I think that reconciliation tools tend to overestimate DTL events when something else than DTL events is going on, but I can't tell if that really applies to your case. 
I hope I can help you better in January!

Benoit

**Comment by Jigyasa3** [comment]
Hey @BenoitMorel!

Thank you so much for acknowledging the message. Please feel free to reply when you are back. If it's okay, I will post some results trying different scenarios of host-symbiont interactions for your feedback when you return.
Happy holidays!

**Comment by Jigyasa3** [comment]
Analysis1- I compared the generax output of a) host-symbiont DTL events with host species having multiple symbionts to b) host-symbiont DTL events with equal no. of host and symbiont tips (similar to Satler et al 2019).

I find that there are 14 host species that are common in both analysis out of 37 DTL events in (a) and 54 DTL events in (b).
Out of these 14 common host species, 22 transfers are to the same receiving nodes/tips in both analysis.

My questions from this analysis are: 
1. There are 3 transfer events that are from younger host tips to ancestral ones (i.e back transfers), can they be trusted?
2. And, can I use the combined results (as done here) to discuss DTL events in my host-symbiont tree? Would this be a more conservative analysis reducing false positives or is it completely wrong?

**Comment by BenoitMorel** [comment]
Hello,

I have quickly read the paper from Satler et al. 

If the analysis between gene-species evolution and host-symbionts evolution works (which is out of the scope of my expertise):

1. Unfortunately, GeneRax only implements an undated model that does not forbid "impossible transfers" (unlike the dated model implemented in ALE).  There are several kinds of "back transfers" between two host lineages A and B:
- B is a parent of A -> this is clearly impossible in practice and reflects an error in the inference.
- B and A are known to be not contemporary, and B is older than A. This is also impossible, but one has to be sure that A and B are not contemporary to reject this scenario.
- A is a tip, B is an "ancestral" (internal) node. This is possible if the lineages of A and B potentially co-existed (were contemporary) during an interval of time. Those transfers might seem to go back in time when viewed in a reconciliation viewer, but those viewer usually do not account for host tree branch lengths which can be misleading.

2. Do analysis 1 and 2 respectively correspond to the split and pruned datasets from the Satler paper? If yes, I would rather trust the split dataset that does not discard any data. If you can reproduce the same result with both datasets, I think it makes the result stronger. 

Best,
Benoit

**Comment by BenoitMorel** [comment]
I am closing this. Please reopen if you need further help!
