### ISSUE TITLE
Generax results interpretation

### ISSUE THREAD

**Issue by Uzunmasha** [BenoitMorel/GeneRax#42]
Hello Benoit!
I tried to run generax on data from my research, and the results seemed very strange to me. Can I ask you some questions about them?
I study magnetotactic bacteria. These bacteria synthesize nanomagnets called magnetosomes.
To date, genes for magnetosome synthesis have been found in genomes from several different phyla, and I would like to study their evolution.
I built a species tree and rooted it (species_tree.nwk in attached files). I also have a fasta file with genes of magnetosome synthesis (for example, MamA is one of these genes) and ran generax with this code:
python /path/to/generax/build_families_file.py /path/to/generax/alignment/MamA/ NONE NONE LG+I+F+G4 /path/to/generax/families/families_mamA.txt
mpiexec -np 4 generax -f /path/to/generax/families/families_mamA.txt -s /path/to/generax/species_tree/species_tree.nwk --rec-model UndatedDTL --reconcile -p /path/to/generax/output/output_mamA
And I got as a result a file with DTLs (PDF attached).
Could you please tell me is it normal that the DTL lines are outside the species tree? Or am I doing something wrong?
Also, some genomes have 2 MamA genes, which control the synthesis of different magnetosomes. Do I understand correctly that these genes need to be named as species-name_gene1 and species-name_gene2?

Thanks in advance,
Maria

[MamA_reconcilliated.pdf](https://github.com/BenoitMorel/GeneRax/files/5724559/MamA_reconcilliated.pdf)
[mamA1.txt](https://github.com/BenoitMorel/GeneRax/files/5724575/mamA1.txt)
[species_tree1.txt](https://github.com/BenoitMorel/GeneRax/files/5724580/species_tree1.txt)

**Comment by BenoitMorel** [comment]
Dear Maria,

I will only give you a quick answer for now and I will look at this more carefully after my vacations.
My first guess is that there are so many genes and species that the viewer is overwhelmed. The viewer was developed in another lab and i can't tell for sure, but I have already seen it failing (for instance when there were too many gene copies along one species lineage).
Could you please send me the xml file you obtained?

If by chance you know about any better reconciliation viewers that support duplication and transfers, I would be happy to add the corresponding format to the GeneRax outputs. 

Cheers,
Benoit

**Comment by Uzunmasha** [comment]
Dear Benoit,
This is my xml file
[mamA_reconciliated.zip](https://github.com/BenoitMorel/GeneRax/files/5726137/mamA_reconciliated.zip)
Happy holidays to you!
I don't know a better reconciliation viewer, but I will try to find something.
 
Best,
Maria

**Comment by Uzunmasha** [comment]
Dear Benoit,
I found my mistake - the species tree in newick should be without bootstraps.
Everything is ok now

Best,
Maria
