### ISSUE TITLE
"reconciliations" folder missing

### ISSUE THREAD

**Issue by bpucker** [BenoitMorel/GeneRax#43]
Hi Benoit,

Thank you for developing such a nice tool. I ran GeneRax and was surprised that some of the described output files are missing. There are no errors reported in any of the log files. Finally, I found the issue #31 in which you explain that the "reconciliations" folder can be missing if the "--reconcile" flag is not used. I was told by a colleague that this issue is fixed in the latest version. It turns out that my installation via conda is v1.1.0 and apparently not the latest version. If you are already aware of this problem, feel free to close this issue directly.

Best wishes,
Boas

**Comment by BenoitMorel** [comment]
Dear Boas,

Thank you for your nice feedback.
This should indeed correspond to issue 31 and be fixed in the latest
version (currently 1.2.2).
Please let me know if either adding the --reconcile flag or updating
generax fixes the issue. I apologize for the trouble.

Best wishes,
Benoit

Le lun. 18 janv. 2021 à 10:31, Boas Pucker <notifications@github.com> a
écrit :

**Comment by bpucker** [comment]
Sorry, I forgot to mention that I installed GeneRax last week via conda and it is v1.1.0. My point is that the version distributed via conda seems to be outdated. Now, I am using the --reconcile flag and assume that it will work.

Best,
Boas

**Comment by BenoitMorel** [comment]
Ok, I will have a look at this in the next few days then!

Le lun. 18 janv. 2021 à 10:52, Boas Pucker <notifications@github.com> a
écrit :

**Comment by BenoitMorel** [comment]
Dear Boas,

I tried installing generax via conda and got the 1.2.2 version installed.
Could you please check the version number with those two commands:
`conda list | grep generax`
`generax --help`

Can you also tell me if anything changes after calling
`conda update generax`

Thanks,
Benoit

**Comment by bpucker** [comment]
Hi Benoit,

I already compiled the latest GeneRax version. Therefore, I am able to run v1.2.2 and everything works well.

However, the GeneRax version installed via conda is v1.1.0 and running the update does not change that. Here is the full output of running conda list | grep generax (after running the update):

generax                   1.1.0                h78e549b_0    bioconda

I am surprised that the update is not working for me while you are able to get the latest version via conda.

Best wishes,
Boas

**Comment by BenoitMorel** [comment]
Dear Boas,

Yes, this is strange. I am not expert in conda so I am not sure about what could cause the issue. 
After googling the problem, I have found some other conda users experiencing the same kind of problem. Although I still don't understand what causes this, those various fixes worked for some conda users:
- conda install <pkg>=<version>
- conda update --all
- uninstall and reinstall the package

If the manual installation is enough for you, I suggest that you close the issue, and I will wait to see if any other user encounters the same issue. If not, just let me know and we can try to investigate further. 

Best wishes,
Benoit

**Comment by bpucker** [comment]
Dear Benoit,

Thank you very much for these additional suggestions. Unfortunately, none of the options works for me. Even uninstalling and reinstalling the package is not changing the version. I agree that this issue should be closed.

Best wishes,
Boas

**Comment by bpucker** [comment]
Compiling the latest version is a suitable alternative to the installation via conda.
