### ISSUE TITLE
Recommended reconciliation model

### ISSUE THREAD

**Issue by NatJWalker-Hale** [BenoitMorel/GeneRax#44]
Hi Benoit, 

Firstly, thanks for a great tool, really helpful and easy to use!

Secondly, I was idly perusing the wiki and saw (under SpeciesRax), that you recommend the use of UndatedDTL over UndatedDL even in cases where there is no horizontal transfer expected. I was wondering if this applies only to the (to-be-released) species tree inference, or if it is also recommended when inferring reconciliations on a previously inferred species tree? We are working with a plant group where we expect no transfer events, so have been using UndatedDL until now.

Thanks in advance for your help!

Nat

**Comment by BenoitMorel** [comment]
Hi Nat,

Many thanks for your kind feedback.

This only applies to the unreleased species tree inference tool.
So in your case, you should use the UndatedDL model and ignore all recommendations that you have found on this page. I will clarify this in the wiki to avoid any confusion :-)

Benoit

**Comment by NatJWalker-Hale** [comment]
Hi Benoit, 

Fantastic, thanks for the clarification! 

Best, 

Nat
