### ISSUE TITLE
What is the --reconciliation-samples parameter doing? 

### ISSUE THREAD

**Issue by NatJWalker-Hale** [BenoitMorel/GeneRax#47]
Hi Benoit, 

Sorry for yet another simple question. This one is pretty explanatory. I've read through the paper and the documentation again and can't find reference to the parameter. I've done runs with and without, and found differences in `_events.nwk`, and seen the newly generated files when running with `--reconciliation-samples 100`. However, I didn't fix the seed, so couldn't say if differences in the reconciliation were truly due to that difference. Is it sampling the likelihood space of the reconciliations? 

Thanks very much! 

Nat

**Comment by BenoitMorel** [comment]
Hi Nat,

That's a good question. This feature was a request from a collaborator and I don't think that I have documented it yet.
By default, given a rooted species tree and the corrected gene tree, GeneRax outputs the maximum likelihood reconciliation scenario. However, there are many possible alternative scenarios. When you set  `--reconciliation-samples 100`, GeneRax will return a reconciliation scenario distribution with `100` samples.
Note that this solution is imperfect, in the sense that it samples the reconciliation scenarios from the maximum likelihood gene tree. A better solution would also sample the gene trees to have a real picture of the reconciliation scenarios distribution. But this is not possible with GeneRax.

An additional comment regarding the seed: there is a default seed, so if you run the exact same command twice, it should produce the exact same result. (and it looks like I also forgot to document the seed!)

I will update the wiki soon.
Benoit

**Comment by NatJWalker-Hale** [comment]
Hi Benoit, 

Thanks very much for the clarification, that's very helpful. 

Cheers, 

Nat
