### ISSUE TITLE
Support values

### ISSUE THREAD

**Issue by fmarletaz** [BenoitMorel/GeneRax#52]
Hi - 
Thanks against for the great tool. I have a rather naive question: what are the support values in the reconciliated trees? 
Best

Ferdi

**Comment by BenoitMorel** [comment]
Hi Ferdi,
Do you mean in the .nhx files? There shouldn't be support values, and if
there are some, they are meaningless. In my test files, I see null support
values. If you see different values, they might come from the initial
support values from your starting gene trees.
Adding some confidence score is in my todolist, but that's not a trivial
topic (the bootstrapping technique used in tools such as raxml is not
straightforward to apply to our joint likelihood approach).
Best,
Benoit

Le jeu. 6 mai 2021 à 20:03, Ferdinand Marlétaz ***@***.***> a
écrit :

**Comment by BenoitMorel** [comment]
Hi Ferdi, 

I am closing the issue. Feel free to reopen it if needed.

Best,
Benoit
