### ISSUE TITLE
Where is species tree for example

### ISSUE THREAD

**Issue by SouthernCD** [BenoitMorel/GeneRax#54]
Hi, thanks for the great tools, but when I want to use the example for gene_tree_correction, I failed to the species tree. It is should in "data/plants/species_trees/speciesTree.newick", but not~

**Comment by BenoitMorel** [comment]
Hi,

You are right, thanks a lot for reporting this. I forgot to add two files to github.
It should be fixed now, you can update the repository with `git pull` and try running the examples again.

Benoit

**Comment by SouthernCD** [comment]
Thank you : ) ~~

**Comment by BenoitMorel** [comment]
You're welcome :-)
