### ISSUE TITLE
Broken installation

### ISSUE THREAD

**Issue by mesti90** [BenoitMorel/GeneRax#57]
It seems to me that with gcc version 10.3.0 (ubuntu) a minor change should be made in src/core/IO/Model.hpp

The following error is raised:
```

/GeneRax/src/core/IO/Model.hpp: In member function 'void SubstitutionModel::base_freqs(const doubleVector&)':
/GeneRax/src/core/IO/Model.hpp:75:18: error: 'invalid_argument' is not a member of 'std'

```
If you add to the preamble

```
#include <stdexcept>
```

the installation will be flawless.

This is not an issue with gcc version 9.3.0

**Comment by BenoitMorel** [comment]
Hi mesti90,

thanks a lot for the report and for providing a fix :-)
I have added the include in Model.hpp (https://github.com/BenoitMorel/GeneRax/commit/042a8977878879f7eb4cad9a67556d86c505f9d8)
The fix is available in the master branch.

Benoit

**Comment by mesti90** [comment]
Thanks for the quick fix of the code
