### ISSUE TITLE
Trailing whitespaces in MSA labels considered significant

### ISSUE THREAD

**Issue by delehef** [BenoitMorel/GeneRax#64]
Currently, GeneRAX consider trailing whitespaces in FASTA-formatted MSA label to be indeed part of the label. 

This leads to confusing error messages, where GeneRAX seems to be complaining about the exact same genes missing both in the tree and the alignment, and the only clue is the double spacing of the ‶missing″ genes in the tree.

```
[00:00:00] Filtering invalid families...
// Notice the double spacing between gene names...
Absent in the gene tree: ENSJJAP00000024216  ENSCHAP00000048618  ENSDCDP00000033911  ENSMMDP00005048983 [...]
// ...and here they are single spaced
Absent in the alignment: ENSLOCP00000008274 ENSDCDP00000033911 ENSECRP00000031929 [...] 
```

It's a technically correct parsing of the FASTA file, but I can't think of a legitimate use case of trailing whitespaces in FASTA labels that are not an artefact from the script generating them.

Maybe it would be better to either strip these whitespaces or to issue a warning when they are detected.

**Comment by BenoitMorel** [comment]
Hello, thanks for your message. Can you send me such an alignment?

**Comment by delehef** [comment]
Sure thing, here is a minimal reproducible example; please just extract
it and run
```
generax -f doit.generax -s SpeciesTree.nhx -p out
```

Note that if you remove the trailing spaces in the header of
`41219.fap`, then everything works fine.

**Comment by BenoitMorel** [comment]
Thank you so much for the report and the example. It's indeed very difficult for users to spot this... I decided not to automatically drop the spaces but rather to improve the error message to make it easier to spot the trailing whitespaces. The message now looks like:
```
Absent in the gene tree: 'ENSHHUP000000523143 ' 'ENSSSAP00000008713 ' 'ENSHHUP00000052311 '
Absent in the alignment: 'ENSHHUP000000523143' 'ENSHHUP00000052311' 'ENSSSAP00000008713'
```

**Comment by delehef** [comment]
Thanks!
