### ISSUE TITLE
Error: Input alignment file does not exist

### ISSUE THREAD

**Issue by purple49** [BenoitMorel/GeneRax#68]
Hello,

I'm getting an error where none of my protein alignment files in fasta format seem to exist. Based on previous threads, I don't think the issue is with forbidden characters and I'm a bit stuck as to what the problem might be. This is the command I used with generax: 

`generax --families compiled_families.txt --species-tree RAX_LGG.raxml.bestTree --rec-model UndatedDL --prefix correction --strategy SPR`

Attached are a subset of the gene trees, alignment, mapping, families files I used, as well as the logged output from generax. 

Thank you so much!

[generax_subset.zip](https://github.com/BenoitMorel/GeneRax/files/13262830/generax_subset.zip)

**Comment by BenoitMorel** [comment]
Hello,
GeneRax cannot find the alignment file, so I would rather look at the path
to the alignment files in the family file. Can you try to move the files
such that there is no space in the path? Maybe that's causing the issue.
Best,
Benoit

**Comment by purple49** [comment]
I've tried to remove the spaces in the file path as well as moving the files to a path with no spaces but the problem is still persisting.

**Comment by BenoitMorel** [comment]
It's really hard to tell. I won't be able to reproduce on my machine since
the paths won't work. Stupid idea, but have you checked that if you copy
paste the path to the alignment (from your file) and try to open it (e.g.
cat filepath), the path is correct?

**Comment by BenoitMorel** [comment]
Oh wait, I just thought: what if you remove the quotes around the file path?

**Comment by purple49** [comment]
That worked! Thank you so much!
