### ISSUE TITLE
Specifying number of cores

### ISSUE THREAD

**Issue by samsonweiner** [BenoitMorel/GeneRax#74]
Hi there,

Is there a parameter which specifies the number of cores? If not, will it automatically distribute over available cores?

Thank you for your help.

- Samson

**Comment by BenoitMorel** [comment]
Hi Samson,
Yes, you need to call:
 mpiexec -np NUMBER_OF_CORES build/bin/generax [arguments]
See the first line of
https://github.com/BenoitMorel/GeneRax/wiki/GeneRax#command-line-interface
Best,
Benoit

Le ven. 19 janv. 2024 à 20:31, samsonweiner ***@***.***> a
écrit :

**Comment by samsonweiner** [comment]
Ah, I missed have missed that. Thanks. I'll go ahead and close the thread.
