### ISSUE TITLE
Assertion '0.0 != new_loglh' failed ?

### ISSUE THREAD

**Issue by KyleTDavid** [BenoitMorel/GeneRax#75]
My run failed at the optimizing gene trees step with the following error:

`generax: /opt/conda/conda-bld/generax_1582495041618/work/src/core/likelihoods/LibpllEvaluation.cpp:211: static double LibpllEvaluation::optimizeAllParametersOnce(pllmod_treeinfo_t*, double): Assertion '0.0 != new_loglh' failed.`

Do you have insight as to what this might mean? I would upload my input files but they are quite large (~3k trees), and it seems to  run fine on a smaller subset.

**Comment by BenoitMorel** [comment]
Hi Kyle,
I really don't know, I don't think I can fix this without reproducing. I
suspect that one (or a few) specific alignments are causing the issue, but
I have no idea why. You could either send me everything, or try to find a
small subset of families that causes the issue (split the families in two,
pick one half that still causes the issue, and continue until it's a small
set).
Best,
Benoit

Le ven. 26 janv. 2024 à 18:30, Kyle David ***@***.***> a
écrit :

**Comment by KyleTDavid** [comment]
Hey Benoit,

Thanks for your quick response and continued patience. I will start hunting for the problem alignments as you suggest, here is the full dataset in case you wanted to take a look, executed using `generax -s SpeciesTree.txt -f config.txt`

https://drive.google.com/file/d/1WdITB8Qh2Yi3LRQ5ktEs_uLeJwm684j0/view?usp=sharing

**Comment by KyleTDavid** [comment]
Still getting lots of weird errors but I switched to another cluster and things are running fine there, so I assume it was some issue on my end. Closing now, thanks again!
